In [1]:
#import pandas library
import pandas as pd

In [10]:
#load dataset
df=pd.read_csv("intern/01.Data Cleaning and Preprocessing.csv")
df

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,NaN,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,NaN,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,NaN,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,NaN,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,NaN,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,12-09:00,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29
297,12-10:00,24.98,NaN,85.034,1278.345,368.564,357.723,321.387,NaN,520.365,...,65.729,332.523,307.169,151.544,905.639,1344.469,418.979,48.135,251.614,30.47
298,12-11:00,21.00,NaN,88.013,1307.722,278.842,357.438,323.757,NaN,553.070,...,65.795,331.263,306.400,157.954,908.691,1344.588,462.712,54.373,251.197,NaN
299,12-12:00,21.40,NaN,85.490,1255.986,273.484,361.365,322.689,NaN,590.199,...,71.456,333.032,308.732,174.069,986.206,1348.747,457.313,53.194,251.324,30.46
300,31-05:00,20.89,14.308,94.172,1327.832,251.120,351.263,332.485,1.522,631.514,...,71.286,328.699,300.706,180.229,903.605,1323.082,232.729,54.503,250.084,NaN

In [13]:
#calculate the info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      291 non-null    object
 1   Y-Kappa          301 non-null    float64
 2   ChipRate         297 non-null    float64
 3   BF-CMratio       287 non-null    float64
 4   BlowFlow         288 non-null    float64
 5   ChipLevel4       300 non-null    float64
 6   T-upperExt-2     300 non-null    float64
 7   T-lowerExt-2     300 non-null    float64
 8   UCZAA            277 non-null    float64
 9   WhiteFlow-4      300 non-null    float64
 10  AAWhiteSt-4      160 non-null    float64
 11  AA-Wood-4        300 non-null    float64
 12  ChipMoisture-4   300 non-null    float64
 13  SteamFlow-4      300 non-null    float64
 14  Lower-HeatT-3    300 non-null    float64
 15  Upper-HeatT-3    300 non-null    float64
 16  ChipMass-4       300 non-null    float64
 17  WeakLiquorF      300 non-null    float64
 18  BlackFlow-2      300 non-null    float64
 19  WeakWashF        300 non-null    float64
 20  SteamHeatF-3     300 non-null    float64
 21  T-Top-Chips-4    300 non-null    float64
 22  SulphidityL-4    160 non-null    float64
dtypes: float64(22), object(1)
memory usage: 54.2+ KB

In [15]:
#caculating the sum
df.isnull().sum()

Observation         10
Y-Kappa              0
ChipRate             4
BF-CMratio          14
BlowFlow            13
ChipLevel4           1
T-upperExt-2         1
T-lowerExt-2         1
UCZAA               24
WhiteFlow-4          1
AAWhiteSt-4        141
AA-Wood-4            1
ChipMoisture-4       1
SteamFlow-4          1
Lower-HeatT-3        1
Upper-HeatT-3        1
ChipMass-4           1
WeakLiquorF          1
BlackFlow-2          1
WeakWashF            1
SteamHeatF-3         1
T-Top-Chips-4        1
SulphidityL-4      141
dtype: int64

In [16]:
#calculating the duplicates
duplicates=df[df.duplicated()]
duplicates
len(duplicates)

0

In [18]:
#calculating the shape
df.shape

(301, 23)

In [19]:
df=df.drop_duplicates()
df.shape

(301, 23)

In [20]:
#calculating the duplicates
duplicates=df[df.duplicated()]
duplicates
len(duplicates)

0

In [21]:
df.iloc[0:10,0]=None
df.info

<bound method DataFrame.info of     Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4   \
0          None    23.10    16.520     121.717  1177.607      169.805
1          None    27.60    16.810      79.022  1328.360      341.327
2          None    23.19    16.709      79.562  1329.407      239.161
3          None    23.60    16.478      81.011  1334.877      213.527
4          None    22.90    15.618      93.244  1334.168      243.131
..          ...      ...       ...         ...       ...          ...
296    12-09:00    20.90    15.167      84.640  1283.706      339.440
297    12-10:00    24.98       NaN      85.034  1278.345      368.564
298    12-11:00    21.00       NaN      88.013  1307.722      278.842
299    12-12:00    21.40       NaN      85.490  1255.986      273.484
300    31-05:00    20.89    14.308      94.172  1327.832      251.120

     T-upperExt-2   T-lowerExt-2    UCZAA  WhiteFlow-4   ...  SteamFlow-4   \
0          358.282         329.545  1.443       599.253  ...        67.122
1          351.050         329.067  1.549       537.201  ...        60.012
2          350.022         329.260  1.600       549.611  ...        61.304
3          350.938         331.142  1.604       623.362  ...        68.496
4          351.640         332.709    NaN       638.672  ...        70.022
..             ...             ...    ...           ...  ...           ...
296        354.803         311.041  1.635       532.419  ...        65.561
297        357.723         321.387    NaN       520.365  ...        65.729
298        357.438         323.757    NaN       553.070  ...        65.795
299        361.365         322.689    NaN       590.199  ...        71.456
300        351.263         332.485  1.522       631.514  ...        71.286

     Lower-HeatT-3  Upper-HeatT-3   ChipMass-4   WeakLiquorF   BlackFlow-2   \
0          329.432         303.099      175.964      1127.197      1319.039
1          330.823         304.879      163.202       665.975      1297.317
2          329.140         303.383      164.013       677.534      1327.072
3          328.875         302.254      181.487       767.853      1324.461
4          328.352         300.954      183.929       888.448      1343.424
..             ...             ...          ...           ...           ...
296        332.924         307.626      145.299       832.906      1344.708
297        332.523         307.169      151.544       905.639      1344.469
298        331.263         306.400      157.954       908.691      1344.588
299        333.032         308.732      174.069       986.206      1348.747
300        328.699         300.706      180.229       903.605      1323.082

     WeakWashF   SteamHeatF-3   T-Top-Chips-4   SulphidityL-4
0       257.325         54.612         252.077             NaN
1       241.182         46.603         251.406           29.11
2       237.272         51.795         251.335             NaN
3       239.478         54.846         250.312           29.02
4       215.372         54.186         249.916           29.01
..          ...            ...             ...             ...
296     388.911         49.524         251.833           30.29
297     418.979         48.135         251.614           30.47
298     462.712         54.373         251.197             NaN
299     457.313         53.194         251.324           30.46
300     232.729         54.503         250.084             NaN

[301 rows x 23 columns]>

In [24]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      291 non-null    object
 1   Y-Kappa          301 non-null    float64
 2   ChipRate         297 non-null    float64
 3   BF-CMratio       287 non-null    float64
 4   BlowFlow         288 non-null    float64
 5   ChipLevel4       300 non-null    float64
 6   T-upperExt-2     300 non-null    float64
 7   T-lowerExt-2     300 non-null    float64
 8   UCZAA            277 non-null    float64
 9   WhiteFlow-4      300 non-null    float64
 10  AAWhiteSt-4      160 non-null    float64
 11  AA-Wood-4        300 non-null    float64
 12  ChipMoisture-4   300 non-null    float64
 13  SteamFlow-4      300 non-null    float64
 14  Lower-HeatT-3    300 non-null    float64
 15  Upper-HeatT-3    300 non-null    float64
 16  ChipMass-4       300 non-null    float64
 17  WeakLiquorF      300 non-null    float64
 18  BlackFlow-2      300 non-null    float64
 19  WeakWashF        300 non-null    float64
 20  SteamHeatF-3     300 non-null    float64
 21  T-Top-Chips-4    300 non-null    float64
 22  SulphidityL-4    160 non-null    float64
dtypes: float64(22), object(1)
memory usage: 54.2+ KB

In [25]:
df.to_csv("intern/01.Data Cleaning and Preprocessing.csv",index=False)